name: Build, Test and Deploy

on:
  push:
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.6'
    - name: Build
      run: go build -v ./...
    - name: Add Cover
      run: go get golang.org/x/tools/cmd/cover
    - name: Test
      run: go test -race -coverprofile=coverage.out -covermode=atomic
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Deploy to pkg.go.dev
      run: GOPROXY=proxy.golang.org go list -m github.com/darnfish/email-forward-parser@$GITHUB_REF_NAME
